1、导入numpy作为np，并查看版本
难度等级：L1
问题：将numpy导入为 np 并打印版本号。

In [1]:
import numpy as np
print(np.__version__)

1.16.2


2、如何创建一维数组？
难度等级：L1
问题：创建从0到9的一维数字数组

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. 如何创建一个布尔数组？
难度等级：L1

问题：创建一个numpy数组元素值全为True（真）的数组

In [8]:
arr1 = np.full((3,4), True, dtype=bool)
arr1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

4. 如何从一维数组中提取满足指定条件的元素？
难度等级：L1

问题：从 arr 中提取所有的奇数

In [10]:
arr3 = arr[arr%2 == 1]
arr3

array([1, 3, 5, 7, 9])

4. 如何从一维数组中提取满足指定条件的元素？
难度等级：L1

问题：从 arr 中提取所有的奇数

In [13]:
arr[arr%2 == 1]=-1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. 如何在不影响原始数组的情况下替换满足条件的元素项？
难度等级：L2

问题：将arr中的所有奇数替换为-1，而不改变arr。

In [14]:
arr = np.arange(10)

out = np.where(arr%2==1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7. 如何改变数组的形状？
难度等级：L1

问题：将一维数组转换为2行的2维数组

In [17]:
arr = np.arange(10)
arr4 = arr.reshape(2,-1)
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. 如何垂直叠加两个数组？
难度等级：L2

问题：垂直堆叠数组a和数组b

给定：

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [18]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. 如何水平叠加两个数组？
难度等级：L2

问题：将数组a和数组b水平堆叠。

给定：

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

In [19]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])